spring:
  datasource:
    url: jdbc:mysql://120.79.223.29/mybatis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: new_password

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update   # 更新表结构
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

